### ISSUE TITLE
Sounds – todo list

### ISSUE THREAD

**Issue by palrogg** [PolipGames/Edgar#17]
- [x] Platform sounds: must stop and play again when collision with player
- [x] Manage when to create / remove sounds attached to aliens
- [x] Complete sound manager
- [ ] Write this list better
