### ISSUE TITLE
Todo 10 mai

### ISSUE THREAD

**Issue by palrogg** [PolipGames/Edgar#19]
- [x] Afficher bouton quand on passe par l’intro
- [x] Fix textes de l’intro
- [x] Tester sans tutoriel
- [x] Export vidéo

**Comment by palrogg** [comment]
+ ajout rectangle de fond au sous-titre
+ plus de memory warning (scène créée trop tôt, reste de la 1e version)
