### ISSUE TITLE
Checklist for submission

### ISSUE THREAD

**Issue by palrogg** [PolipGames/Edgar#4]
# Before the App Store submission
- [x] Good screenshot set
- [x] Record video
- [x] Cut video (duration: 30 seconds)
- [x] Enhance description
- [x] German and French description
- [x] Credits revision

**Comment by palrogg** [comment]
# Current credits

Find our source code and assets: github.com/polipgames/Edgar
Explanations on Facebook: facebook.com/edgartheexplorer/
Contact us at polipgames@gmail.com!

By Filipe Mathez and Paul Ronga
Many thanks to Aymeric, Justine, Kathryn, Liv and Steeve
Special thanks to our girlfriends
Very special thanks to our mums

Source code: GNU Lesser General Public License 2.1 http://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html
Images: CC-BY http://creativecommons.org/licenses/by/4.0/

Music:
“Juno” by Chronox, CC-BY: http://creativecommons.org/licenses/by/4.0/
“X Files theme remixed to 8 bit” by arandompersona, CC-BY: http://creativecommons.org/licenses/by/3.0/

# Current description

Free/libre platformer, no ads. Your goal: to collect evidences of illegal experiments on alien beings in an underground laboratory.
Run left, right, jump and stop to find your path, using carriages and elevators. Avoid contamination from escaped aliens. Beware of time-consuming traps: the stopwatch makes the score!
Find our source code (LGPL) and assets (Creative Commons) on: http://github.com/EdgarTheExplorer
Contact us at polipgames@gmail.com!
Filipe Mathez and Paul Ronga

**Comment by palrogg** [comment]
[French version - updated and pasted below]

**Comment by palrogg** [comment]
Oder better, Du:
Gratis, Werbung freies Jump ’n’ Run. Edgar, ein alter Schnauzbart-Träger (Du), soll ein geheimes Laboratorium untersuchen. Er gehört zu Greenalien, eine Organisation, die gegen Alienversuche kämpft.
Finde deinen Weg durch Sperren und Finsternis. Versuch, das Geschwindigkeitsrekord zu schlagen oder spiel mit Loren und Aufzüge: Es ist dein Wahl!
Quellcode (LGPL) und Sprites (Creative Commons): http://github.com/EdgarTheExplorer.
Schreib uns an polipgames@gmail.com!
Filipe Mathez und Paul Ronga (513 char)

**Comment by palrogg** [comment]
Free/libre platformer, no ads. Edgar, an old mustached man (you), has to inspect an underground laboratory. He's member of Greenalien, an organisation which fight against experiments on alien beings.
Run left, right, jump and stop to find your path, using carriages and elevators. Avoid contamination from escaped aliens. Beware of time-consuming traps: the stopwatch makes the score!
Find our source code (LGPL) and assets (Creative Commons) on: http://github.com/EdgarTheExplorer
Contact us at polipgames@gmail.com!
Filipe Mathez and Paul Ronga (546 char)

**Comment by palrogg** [comment]
# Edgar the Explorer, platform game

Free/libre platformer, no ads. Edgar, an old mustached activist (you), has to inspect an underground laboratory. He fights against experimentation on alien beings at Greenalien.
- Free movement: left, right, high jump, long jump
- Use minecarts and elevators
- Avoid contamination by escaped aliens
- Rush or explore slowly: it's up to you!
- The stopwatch makes the score
- FOSS (free and open-source): reuse or contribute

Our source code (LGPL) and assets (Creative Commons): http://github.com/EdgarTheExplorer
Contact us at polipgames@gmail.com!
Filipe Mathez and Paul Ronga

**Comment by palrogg** [comment]
# Edgar the Explorer, Jump ’n’ Run

Gratis, Werbung freies Jump ’n’ Run. Edgar, ein alter Schnauzbart-Träger (Du), soll ein geheimes Laboratorium untersuchen. Er kämpft gegen Alienversuche bei Greenalien.
- Freie bewegung: links, rechts, Weitsprung, Hochsprung
- Benutze Loren und Aufzüge
- Vermeide Verseuchung durch überirdische Lebewesen
- Finde deinen Weg durch Sperren und Finsternis
- Das Geschwindigkeitsrekord zu schlagen oder zu explorieren: Es ist dein Wahl

Frei und Open-Source: Wiederverwendung und Mitmachen ist willkommen!

Quellcode (LGPL) und Sprites (Creative Commons): http://github.com/EdgarTheExplorer.

Schreib uns an polipgames@gmail.com!

Filipe Mathez und Paul Ronga

**Comment by palrogg** [comment]
# Edgar the Explorer, jeu de plateforme

Jeu de plateforme gratuit et sans pub. Edgar, un vieil activiste moustachu (vous), a pour mission d'explorer un laboratoire secret. Il lutte contre l'expérimentation extraterrestre chez Greenalien.
- Bougez librement à gauche, à droite, et faites des sauts longs ou hauts
- Utilisez des wagonnets et des plateformes mobiles
- Evitez d'être contaminé par les extraterrestres qui s'échappent
- Battre le record de vitesse ou explorer tranquillement, c'est votre choix

Libre et open-source: réutilisation et contributions bienvenues!

Retrouvez notre code source (LGPL) et nos images (Creative Commons) sur: http://github.com/EdgarTheExplorer.

Ecrivez-nous à polipgames@gmail.com

Filipe Mathez et Paul Ronga

**Comment by palrogg** [comment]
Tags: platformer, platform, libre, FOSS, exploration, 2d

**Comment by palrogg** [comment]
Correct german version!! ❤️ 

Kostenloses und werbefreies Jump ’n’ Run. Edgar, ein alter Schnauzbart-Träger (Du), soll ein geheimes Laboratorium untersuchen. Er kämpft gegen Versuche an Aliens bei Greenalien.

```
• freie Steuerung: links, rechts, Springen weit und hoch
• Fahre mit Loren und Aufzügen
• Vermeide Verseuchung durch entflohene Außerirdische
• Finde deinen Weg durch Sperren und Dunkelheit
• Du spielst gegen die Stoppuhr oderlässt dir Zeit alles zu erkunden - es ist dein Wahl
```

Frei und Open-Source: Wiederverwendung und Mitmachen ist willkommen!

Quellcode (LGPL) und Sprites (Creative Commons): http://github.com/EdgarTheExplorer.

Schreib uns an polipgames@gmail.com!

Filipe Mathez und Paul Ronga
